version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/tecnibilds
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root
      timeout: 64
